### ISSUE TITLE
Different output to handlebars npm precomile?

### ISSUE THREAD

**Issue by ghost** [kawasima/handlebars-maven-plugin#4]
Using the `handlebars` command line utility from NPM to precompile, templates stored under `Handlebars.templates` can be used with a context immediately:

``` javascript
var template = Handlebars.templates['foo'];
var output = template({bar: true});
```

Using your plugin, templates stored under `Handlebars.templates` are the output from `Handlebars.precompile`, so must be passed through the `Handlebars.template` function in order to be used with a context object:

``` javascript
var precompiled = Handlebars.templates['foo'];
var template = Handlebars.template(precompiled);
var output = template({bar: true});
```

I'm interested to know why this is the case?

Thanks

**Comment by sappenin** [comment]
Bump.  I'm having this same issue.

**Comment by frko** [comment]
Looking at `https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/compiler/compiler.js` the latest and greatest npm command should produce the exact same result as this plugin does.

**Comment by kawasima** [comment]
It's my fault...

In HandlebarsEngine.java:l.107

``` java
out.println("templates['" + FilenameUtils.getBaseName(template.getName()) + "']=(" + obj.toString() + ");");
```

It's different from handlebars.js/bin/handlebars.  I correct it as the below in the next version.

``` java
out.println("templates['" + FilenameUtils.getBaseName(template.getName()) + "']=template(" + obj.toString() + ");");
```
